name: aware-net
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Core Python version (matches project requirements)
  - python=3.12  # Compatible with current PyTorch nightly builds

  # Note: PyTorch nightly builds required for compatibility
  # Install after environment creation via pip (see setup_environment.md for details)

  # Model loading and pre-trained models
  - timm  # PyTorch Image Models - for MobileNetV4, EfficientNetV2, GenConViT
  
  # Computer vision and video processing
  - opencv  # Video reading, frame extraction, image resizing
  
  # Data science and evaluation
  - scikit-learn  # AUC, F1-Score calculation and probability calibration
  - pandas  # Data manifest file creation and management
  - numpy  # Fundamental numerical computing
  
  # Machine learning models
  - lightgbm  # Gradient boosting for meta-model training
  
  # Visualization and utilities
  - matplotlib  # Plotting and chart generation
  - seaborn  # Statistical data visualization
  - tqdm  # Progress bars for data processing and training
  
  # Development and analysis tools
  - jupyterlab  # Interactive development and exploratory data analysis
  
  # Additional useful packages
  - pillow  # Image processing library
  - requests  # HTTP requests for downloading datasets

  # Pip dependencies (packages not available through conda)
  - pip
  - pip:
    # GPU Video Processing (Windows optimized)
    - decord  # High-performance GPU video processing for Windows
    
    # Advanced Face Detection (GPU-accelerated backends)
    - insightface  # High-performance GPU face detection (recommended)
    - onnxruntime-gpu  # Required for InsightFace GPU acceleration
    - mediapipe  # Google's optimized face detection with GPU support
    - ultralytics  # YOLOv8 for general object/face detection
    - mtcnn  # Lightweight face detection backup
    
    # Data augmentation and visualization
    - albumentations  # Advanced data augmentation
    - tensorboard  # Training visualization and monitoring
    - wandb  # Experiment tracking and visualization (optional)
    
    # Note: Multiple face detection backends supported for flexibility